# List=[]

In [ ]:
# normal format of List initialization
a = [1,2,3,4,5,6,7,8]
print(a)

print("\n")

# using for loop in list="a"
[i for i in a]

[1, 2, 3, 4, 5, 6, 7, 8]




[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
# In List comprehension --> using 'for loop' & 'if-else' condition
['High' if i>6   else 'low' if i<3   else 'Mid'   for i in a]


#NOTE:
# list comprehension does not support elif 
# Supports only if,else and for

['low', 'low', 'Mid', 'Mid', 'Mid', 'Mid', 'High', 'High']

In [ ]:
# BMI calculator using lambda-function through mapping
weight = [67, 95, 45, 50, 38]
height = [1.65, 1.74, 1.60, 1.40, 1.50]

list(map(lambda x,y : x/y**2, weight, height))
                 #or
list(map(lambda weight,height : weight/height**2, weight, height))


#NOTE:
# bmi=weight/height**2 
# we use map-function to refer x=weight y=height
# we use list to get o/p in form of list 

[24.609733700642796,
 31.37798916633637,
 17.578124999999996,
 25.510204081632658,
 16.88888888888889]

#-----------------------------------------------------------------------------------
#                  Pandas 
### #series (1d)     --> only 1 column
### #data_frame (2d) --> more than 2 columns

1. Pandas were capable of holding any data type.
2. However, Series is sequence of: similar data type, 
similar to array,list or column in table 

In [ ]:
number = range(1,100)

import pandas as pd
pd.Series(number)


#NOTE:
# It gives index as 0,1,2..98 for range 1,2,3,..99 in form of Series

0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

In [ ]:
a = ["Hello", 98, True, 59.874, 'Python']
b = pd.Series(a)
b

#NOTE: 
# pandas were capable of holding any data-type : int,char,float,boolean,etc..,  

0     Hello
1        98
2      True
3    59.874
4    Python
dtype: object

In [ ]:
b[4]

#NOTE:
# By indexing list we access particular data
# INDEX always starts from 0 

'Python'

In [ ]:
import pandas as pd
Subject = ["Maths", "Science", "Tamil", "English", "Social"]
mark = [98, 99, 89, 91, 95]
pd.Series(mark, index = Subject)

#NOTE:
# we informing "pandas_Series" to take index=Subject 

Maths      98
Science    99
Tamil      89
English    91
Social     95
dtype: int64

In [ ]:
Subject = ["Maths", "Science", "Tamil", "English", "Social", "Hindi"]
mark = [98, 99, 89, 91, 95]
for i,j in zip(Subject,mark):
  print(i,j)

#NOTE:
# To avoid value error: len of value does not match len of index 
# we used "zip-function" --> Truncate/avoid the last value=hindi where we didn't give mark

Maths 98
Science 99
Tamil 89
English 91
Social 95


#-----------------------------------------------------------------------------------
# **Dataframe (df)**

In [ ]:
import pandas as pd
Subject = ["Maths", "Science", "Tamil", "English", "Social"]
mark = [98, 99, 89, 91, 95]
df = pd.Series(mark, index = Subject)

#NOTE:
# we assign df to panda series 

array([98, 99, 89, 91, 95])

In [ ]:
df.index

#NOTE:
# To know index of table we call --> "df.index"
# subject as index

Index(['Maths', 'Science', 'Tamil', 'English', 'Social'], dtype='object')

In [ ]:
df.values

#NOTE:
# To know value of table we call --> "df.value"
# mark as value

array([98, 99, 89, 91, 95])

#-----------------------------------------------------------------------------------
# **Dictionaries = {"key" : "val"}**

In [ ]:
b = {"Math":"98", "Science":"99", "Social":"95"}
#for i in b.keys():         #Print "keys" of Dict = b
#  print(i)

#for i in b.values():       #Print "Values" of Dict = b
#  print(i)

for i in b.items():         #Print "items" of Dict = b
   print(i)

('Math', '98')
('Science', '99')
('Social', '95')


In [ ]:
b = {"Math":"98", "Science":"99", "Social":"95"}
pd.Series(b)

#NOTE:
# From dictionary(b) key --> index and value --> value
# pd.Series(b) display dict in form of Series

Math       98
Science    99
Social     95
dtype: object

#-----------------------------------------------------------------------------------
# **Numpy**

### *What is Diff b/w "Numpy array' & 'Normal array'..?*

Numpy array is faster than normal array.
Moreover the structures were same in both.

Execution:
  > array --> 5 seconds

  > Numpy array --> few milli Seconds


Example : 1




In [ ]:
import numpy as np
np.random.randint(1111,9999,1)

#NOTE:
# to get 1 random integer with-in 1111 to 9999
# similar as OTP generation

array([8570])

In [ ]:
import pandas as pd
a = ["English", "Tamil", "Maths", "Science", "Social"]
dic = {"English":91, "Tamil":89, "Maths":98, "Science":99}
df = pd.Series(dic, index = a)
df

#NOTE:
# list --> 5 subjects & dict --> 4 subj-marks
# Here by Assign'g df we request to print all series value(Even missing_data also inclded)

English    91.0
Tamil      89.0
Maths      98.0
Science    99.0
Social      NaN
dtype: float64

In [ ]:
df.isnull()

#NOTE:
# It diplays whether series having "Null value = True" (or) "No Null value = False"

English    False
Tamil      False
Maths      False
Science    False
Social      True
dtype: bool

In [ ]:
df.isnull().sum()

#NOTE:
# Displays how many null-value are present inside series..?

1

In [ ]:
df[df > 97]

#NOTE:
# Used to shortlist & display value based on condition --> i.e., subject mark > 97 [gets printed]

Maths      98.0
Science    99.0
dtype: float64

In [ ]:
df

English    91.0
Tamil      89.0
Maths      98.0
Science    99.0
Social      NaN
dtype: float64

In [ ]:
df["Social"] = 95
df

#NOTE:
# Previous Social has Null value
# Here we updating "Socail" mark ---as---> 95 

English    91.0
Tamil      89.0
Maths      98.0
Science    99.0
Social     95.0
dtype: float64

**## Example : 2**

# < head, tail, min, max, var, std, mean > 

In [ ]:
import pandas as pd
df = pd.Series(range(1,100,5))
df

#NOTE:
# 1st column --> serial number (count)
# 2nd column --> df [start:stop:step]

0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

In [ ]:
df.head(5)

#NOTE:
# Displays [head(5) --> 1st five value] from series

0     1
1     6
2    11
3    16
4    21
dtype: int64

In [ ]:
df.tail(5)

#NOTE:
# Displays [tail(5) --> last five value] from series

15    76
16    81
17    86
18    91
19    96
dtype: int64

In [ ]:
df.min()

#NOTE:
# Displays [min --> minimum value] from series

1

In [ ]:
df.max()

#NOTE:
# Displays [max --> maximum value] from series

96

In [ ]:
df.mean()

#NOTE:
# Displays [mean() ---> Calculates Mean value] from series

48.5

In [ ]:
df.std()

#NOTE:
# Displays [std() ---> Calculates standard variance] from series

29.58039891549808

In [ ]:
df.var()

#NOTE:
# Displays [var() --->Calculates variance] from series

875.0

# **iloc and loc**

1. iloc: Modifying an series --> index position


2.  loc: Modifying an series --> direct index name













In [ ]:
import pandas as pd
Subject = ["Maths", "Science", "Tamil", "English", "Social"]
mark = [98, 99, 89, 91, 95]
df = pd.Series(mark, index = Subject)
df

Maths      98
Science    99
Tamil      89
English    91
Social     95
dtype: int64

In [ ]:
df.iloc[1:]

#NOTE:
# It displays value from 1st index[1:] to last

Science    99
Tamil      89
English    91
Social     95
dtype: int64

In [ ]:
df.iloc[0:2]

#NOTE:
# It displays value b/w [0th index(start) : 2nd index(stop)]
# Index: 0,1 get printed from series

Maths      98
Science    99
dtype: int64

In [ ]:
df.loc['Tamil':]

#NOTE:
# Displays value from index_name['Tamil':] to last
# i.e.., <Tamil, English, Social> 

Tamil      89
English    91
Social     95
dtype: int64

In [ ]:
df.loc['Tamil':'English']

#NOTE:
# Displays value from index_name['Tamil':'English'] to last
# i.e.., <Tamil & English> 

Tamil      89
English    91
dtype: int64

**Example: 3**

# < sorting index >

In [ ]:
df.sort_index(ascending = True)

#NOTE:
# sort our index --> Alphabetical (A-Z) order
# Ascending alphabet index

English    91
Maths      98
Science    99
Social     95
Tamil      89
dtype: int64

In [ ]:
df.sort_index(ascending = False)

#NOTE:
# sort our index --> Alphabetical (Z-A) order
# Descending alphabet index

Tamil      89
Social     95
Science    99
Maths      98
English    91
dtype: int64

 **Example: 4**

# <sorting values(Marks)>

In [ ]:
df.sort_values(ascending = True)

#NOTE:
# sort our mark --> Mark (low to high) order
# Ascending marks value

Tamil      89
English    91
Social     95
Maths      98
Science    99
dtype: int64

In [ ]:
df.sort_values(ascending = False)

#NOTE:
# sort our mark --> Mark (high to low) order
# Descending marks value

Science    99
Maths      98
Social     95
English    91
Tamil      89
dtype: int64

**Example: 5**

# [ rank ---> Descending & Ascending ]


In [ ]:
df.rank(ascending = False)

#NOTE:
# from highest mark it gives Ranking
# DESCENDING wise

Maths      2.0
Science    1.0
Tamil      5.0
English    4.0
Social     3.0
dtype: float64

In [ ]:
df.rank(ascending = True)

#NOTE:
# from lowest mark it gives Ranking
# ASCENDING wise

Maths      4.0
Science    5.0
Tamil      1.0
English    2.0
Social     3.0
dtype: float64

**Example:6**

# Insert, Update, Multiply, Lambda

In [ ]:
import pandas as pd
Subject = ["Maths", "Science", "Tamil", "English", "Social"]
mark = [98, 99, 89, 91, 95]
df = pd.Series(mark, index = Subject)
df

Maths      98
Science    99
Tamil      89
English    91
Social     95
dtype: int64

In [ ]:
df["French"] = 75
df

#NOTE:
# "French" INSERTED in series

Maths      98
Science    99
Tamil      89
English    91
Social     95
French     75
dtype: int64

In [ ]:
df.iloc[5] = 80
df

#NOTE:
# "French mark" get updated using iloc(index) 
# 75 UPDATE as 80

Maths       98
Science     99
Tamil       89
English     91
Social     100
French      80
dtype: int64

In [ ]:
df.loc["Social"] = 100
df

#NOTE:
# "social mark" get updated using loc(position name) 
# 95 gets UPDATE as 100

Maths       98
Science     99
Tamil       89
English     91
Social     100
French      80
dtype: int64

In [ ]:
df1 = df*1000
df1

#NOTE:
# Marks got MULTIPLIED  ---> df*2
# while multiply, add, powerof, etc.., --> Mention "df*14 | df**3 | df+1000" in separate variable name "df1"

Maths       98000
Science     99000
Tamil       89000
English     91000
Social     100000
French      80000
dtype: int64

In [ ]:
df

Maths       98
Science     99
Tamil       89
English     91
Social     100
French      80
dtype: int64

In [ ]:
list(map(lambda x: x+x, df))

#NOTE:
# By LAMBDA function we adding mark again by its respective mark
# i.e., Maths => 98+98 =196

[196, 198, 178, 182, 200, 160]